set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

list(APPEND QT_COMPONENTS_REQUIRED Core HttpServer Test)

find_package(Qt6 6.4 REQUIRED COMPONENTS ${QT_COMPONENTS_REQUIRED})

include_directories(${QT_USE_FILE})
